version: '3.2'

services:

    uniqush:
        container_name: uniqush-server
        image: uniqush-server
        build:
            context: ./
        environment:
            # this is the default, but let's be explicit here
            UNIQUSH_DATABASE_HOST: "redis"
        ports:
            - 9898:9898
        depends_on:
            - redis
    redis:
        container_name: redis
        image: redis