version: '3.2'

services:

    uniqush:
        container_name: uniqush-server
        image: andersonkxiass:uniqush-server
        build:
            context: ./
        environment:
            UNIQUSH_DATABASE_HOST: "redis"
        ports:
            - 9898:9898
        depends_on:
            - redis
        restart: always

    redis:
        container_name: uniqush-redis
        image: redis:alpine
        restart: always